Updated earth patches classification
ITMO-NSS-team/nas-fedot pull request #2
Opened 2022-04-08 09:25 UTC by staeros

updated fies to 0.5.1 fedot version, added changes to CustomGraphModel class so method show now works correctly, added minor chages to create nn model func.

2022-04-08 12:01 UTC, pep8speaks commented
Hello @staeros! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`graph_10cls_patches_classification.py`](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py):

> [Line 13:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 18:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L18): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 19:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L19): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 22:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L22): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 23:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L23): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 26:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L26): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 27:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L27): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 48:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L48): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 66:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L66): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 71:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L71): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> [Line 75:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L75): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 77:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L77): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 85:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L85): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 92:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L92): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 97:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 99:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L99): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 102:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L102): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 105:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L105): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 106:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L106): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 108:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L108): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 111:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L111): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 112:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L112): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 115:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L115): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 118:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L118): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 128:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L128): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 131:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L131): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 136:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L136): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 153:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L153): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 154:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L154): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 155:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_10cls_patches_classification.py#L155): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)

* In the file [`graph_icebergs_classification.py`](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_icebergs_classification.py):

> [Line 12:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_icebergs_classification.py#L12): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 13:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_icebergs_classification.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 17:80](https://github.com/ITMO-NSS-team/nas-fedot/blob/7b7f3350e519de99d62bc53b34a3b2ddcdfd88ec/graph_icebergs_classi [...]

2022-04-08 12:45 UTC, nicl-nno requested changes

2022-04-08 12:45 UTC, nicl-nno commented on graph_10cls_patches_classification.py
> +import os
Все скрипты с примерами стоит вынести в отдельный каталог cases

2022-04-08 12:45 UTC, nicl-nno commented on static_cnn_model.py
> +    return True
А это актуально? Ведь в нейронке могут быть повторяющиеся узлы.

2022-04-08 12:45 UTC, nicl-nno commented on static_cnn_model.py
> +                                layer_params=nn_layer_params)
Если это сборка начального приближения - лучше вынести в отдельную функцию.

2022-04-08 12:45 UTC, nicl-nno commented on static_cnn_model.py
> +import random
А почему это называется static_cnn_model.py, если внутри все равно есть оптимизация?

2022-04-08 12:45 UTC, nicl-nno commented on nas/patches/preprocess.py
> +sys.path.append("C:/Users/aliev/AppData/Local/Programs/Python/Python37/Lib/site-packages/gdal.py")
Локальный путь.

2022-04-08 12:45 UTC, nicl-nno commented on nas/patches/load_images.py
> +    #                            task_type=task_type)
Всё закомментированное надо убрать.

2022-04-08 12:45 UTC, nicl-nno commented on nas/patches/load_images.py
> +def from_images(file_path, num_classes, task_type: TaskTypesEnum = TaskTypesEnum.classification):
А [этот](https://github.com/nccr-itmo/FEDOT/blob/92aede41670e0bff8814d33e54b529137e95d222/fedot/core/data/data.py#L147) метод никак не использовать внутри этой функции?

2022-04-08 12:45 UTC, nicl-nno commented on nas/patches/3classes_preprocess.py
> +def get_images(folder_name):
Кажется этот и соседние с ним методы много раз дублируются в разных скриптах.

2022-04-08 12:45 UTC, nicl-nno commented on nas/graph_nas_node.py
> +        self.layer_params = layer_params
А точно нужен отдельное поле layer_params? Ведь у OptNode есть поле conent['params'].

2022-04-08 12:45 UTC, nicl-nno commented on nas/graph_keras_eval.py
> +        if cnn_nodes_count == chain.cnn_depth:
Лучше вместто chain писать про graph или network (в зависимости от того, что тут по факту)

2022-04-08 12:45 UTC, nicl-nno commented on nas/graph_cnn_gp_operators.py
> +from random import choice, randint
Тут много методов - хорош бы приватные выделить с помощью _

2022-04-08 12:45 UTC, nicl-nno commented on nas/graph_cnn_crossover.py
> +            graph_second.cnn_nodes) - 1 == 0:
Такие сложные проверки лучше разнести по переменным.

2022-04-08 12:45 UTC, nicl-nno commented on nas/composer/graph_gp_cnn_composer.py
> +        return [1]
Тут видимо надо раскомментировать обратно.

2022-04-08 12:45 UTC, nicl-nno commented on nas/composer/graph_gp_cnn_composer.py
> +        pass
Выглядит лишним.

2022-04-08 12:45 UTC, nicl-nno commented on static_cnn_model.py
> +def custom_mutation(graph: OptGraph, **kwargs):
Это актуально для нейронки?

2022-04-08 12:45 UTC, nicl-nno commented on graph_10cls_patches_classification.py
> +    return roc_auc_value, log_loss_value, accuracy_score_value
Выглядит как-то сложно. А методы вычисления metric из fedot-а тут не переиспользовать? Вроде нет нейроночной специфики.

2022-04-08 12:45 UTC, nicl-nno commented on graph_icebergs_classification.py
> +    return graph
Дублирует другой скрипт.

2022-04-08 12:45 UTC, nicl-nno commented on graph_patches_classification.py
> +ROOT = os.path.dirname(os.path.abspath(__file__))
Кажется лучше в функцию вынести поиск корня проекта.

2022-04-08 12:45 UTC, nicl-nno commented on nas/cnn_data.py
> +# from fedot_old.core.repository.task_types import MachineLearningTasksEnum
Старыне комменты остались.

2022-04-08 12:45 UTC, nicl-nno commented on nas/graph_cnn_mutations.py
> +    print(node_depth(graph.root_node) + 1)
Лишние принты и визуализации можно поудалять сразу.

2022-04-12 09:09 UTC, staeros commented on static_cnn_model.py
> +    return True
Уже удалил так как не используется нигде

2022-04-12 11:31 UTC, staeros commented on static_cnn_model.py
> +                                layer_params=nn_layer_params)
Вынес все в отдельную функцию по сборке начального приближения

2022-04-12 11:37 UTC, staeros commented on nas/patches/preprocess.py
> +sys.path.append("C:/Users/aliev/AppData/Local/Programs/Python/Python37/Lib/site-packages/gdal.py")
Осталось от старой версии. Уже удалил, так как больше нигде не используется

2022-04-12 11:38 UTC, staeros commented on nas/patches/3classes_preprocess.py
> +def get_images(folder_name):
Осталось от старой версии. Уже удалил, так как больше нигде не используется

2022-04-12 11:38 UTC, staeros commented on nas/graph_nas_node.py
> +        self.layer_params = layer_params
переписал, теперь параметры хранятся не в отдельном поле layer_params, а в content['params']

2022-04-12 11:41 UTC, staeros commented on graph_10cls_patches_classification.py
> +    return roc_auc_value, log_loss_value, accuracy_score_value
Исправил, свел все в одну функцию в nas.composer.metrics, которая считает rocauc, logloss, accuracy с использованием вычисления метрик из fedot-a

2022-04-12 13:10 UTC, staeros commented on nas/graph_cnn_mutations.py
> +    print(node_depth(graph.root_node) + 1)
Done

2022-04-12 13:10 UTC, staeros commented on nas/cnn_data.py
> +# from fedot_old.core.repository.task_types import MachineLearningTasksEnum
Удалил

2022-04-12 13:11 UTC, staeros commented on graph_patches_classification.py
> +ROOT = os.path.dirname(os.path.abspath(__file__))
Сделал функцию под поиск корня и положил ее в nas.patches.utils

2022-04-12 13:12 UTC, staeros commented on nas/patches/load_images.py
> +def from_images(file_path, num_classes, task_type: TaskTypesEnum = TaskTypesEnum.classification):
переписал с использованием метода from_image из fedot-а

2022-04-12 13:12 UTC, staeros commented on graph_10cls_patches_classification.py
> +import os
сделано

2022-04-12 13:13 UTC, staeros commented on nas/patches/load_images.py
> +    #                            task_type=task_type)
сделано

2022-04-12 13:13 UTC, staeros commented on nas/composer/graph_gp_cnn_composer.py
> +        return [1]
Done

2022-04-12 13:13 UTC, staeros commented on static_cnn_model.py
> +def custom_mutation(graph: OptGraph, **kwargs):
Убрал так как не используется

2022-04-12 13:14 UTC, staeros commented on nas/graph_cnn_gp_operators.py
> +from random import choice, randint
сделано

2022-04-12 13:14 UTC, staeros commented on nas/composer/graph_gp_cnn_composer.py
> +        pass
Удалил

2022-04-12 13:41 UTC, staeros commented on nas/graph_cnn_crossover.py
> +            graph_second.cnn_nodes) - 1 == 0:
Done

2022-04-12 13:41 UTC, staeros commented on graph_icebergs_classification.py
> +    return graph
Убрал

2022-04-12 13:51 UTC, staeros commented on static_cnn_model.py
> +import random
Исправил

2022-04-12 14:11 UTC, nicl-nno commented on cases/static_cnn_model.py
> +    initial_graph = CustomGraphModel()
Странно что он пустой - может None передавать?

2022-04-12 15:07 UTC, nicl-nno commented on nas/composer/graph_gp_cnn_composer.py
> +class CustomGraphModel(OptGraph):
Может переназвать класс более конкретно? NNGraph или как-то так.

2022-04-12 15:07 UTC, nicl-nno commented on nas/composer/graph_gp_cnn_composer.py
> +        self.unique_pipeline_id = str(uuid4())
Кажется это поле больше не нужно.

2022-04-12 15:08 UTC, nicl-nno commented on nas/composer/graph_gp_cnn_composer.py
> +class CustomGraphNode(NNNode):
Аналогично комментарию про название выше.

2022-04-12 15:09 UTC, nicl-nno commented on nas/composer/graph_gp_cnn_composer.py
> +        return [1]
Вроде осталось как было. Если надо переодически отключать - можно реализовать более удобный вариант (например, при передаче пустой metric_function не не делать fit)

2022-04-12 15:35 UTC, staeros commented on nas/composer/graph_gp_cnn_composer.py
> +class CustomGraphNode(NNNode):
Переименовал

2022-04-12 15:36 UTC, staeros commented on nas/composer/graph_gp_cnn_composer.py
> +        return len(nodes)
Убрал

2022-04-12 15:36 UTC, staeros commented on nas/composer/graph_gp_cnn_composer.py
> +        self.unique_pipeline_id = str(uuid4())
Удалил

2022-04-12 15:36 UTC, staeros commented on nas/composer/graph_gp_cnn_composer.py
> +class CustomGraphModel(OptGraph):
переименовал

2022-04-12 16:28 UTC, nicl-nno approved these changes
Только данные надо поменять на более сбалансированные.

2022-04-12 16:43 UTC, merged