Skip connections support
ITMO-NSS-team/nas-fedot pull request #4
Opened 2022-04-25 15:16 UTC by staeros

Added ability to generate graphs with skip connections

2022-04-26 11:17 UTC, nicl-nno requested changes

2022-04-26 11:17 UTC, nicl-nno commented on cases/graph_icebergs_classification.py
> +        mutation_types=[single_edge_mutation],
А это нормально, что тут только edge-мутация?

2022-04-26 11:17 UTC, nicl-nno commented on cases/graph_patches_classification.py
> +        log=default_log(logger_name='Bayesian', verbose_level=1))
Название лога явно нет то.

2022-04-26 11:17 UTC, nicl-nno commented on cases/graph_patches_classification.py
> +    print('save best graph structure...')
Хорошо бы сохранять не только картинку, но и сам грам структуры (через .save()). Да и историю опимизации тоже.

2022-04-26 11:17 UTC, nicl-nno commented on cases/graph_patches_classification.py
> +    path = os.path.join(root, '_compressed_Generated_dataset.pickle')
Странное название с подчеркивания.

2022-04-26 11:17 UTC, nicl-nno commented on cases/static_cnn_model.py
> +def add_skip_connections(graph: NNGraph):
А эта функция точно нужна именно в cases? Может её вынести куда-то в ядро?

Также хорошо бы ей дать описание в docstring-е.

2022-04-26 11:17 UTC, nicl-nno commented on cases/static_cnn_model.py
> +def create_graph(graph: NNGraph, node_type: str, params: dict, parent=None, residual_parent=None,
Аналогично - эта функция только в этом примере нужна?

2022-04-26 11:17 UTC, nicl-nno commented on nas/graph_cnn_gp_operators.py
> +    if node.layer_params["pool_size"]:
Лучше одинарные кавычки использовать.

2022-04-26 11:17 UTC, nicl-nno commented on nas/graph_cnn_gp_operators.py
> +    skip_connection_prob = 35
Мне кажется понятней будет задать как 0.35, чтобы вероятность было от 0 до 1.

2022-04-26 11:17 UTC, nicl-nno commented on nas/graph_cnn_gp_operators.py
> +                graph.nodes[destination_node_id].nodes_from.append(graph_node)
Выглядит как будто в части случаев (если вероятность ни разу не даст зайти в условие is_residual) будет ошибка, что граф ноде не определено

![image](https://user-images.githubusercontent.com/5711814/165287655-b43fd9c8-e4e4-4913-8be2-0380620ea8c2.png)

2022-04-26 11:17 UTC, nicl-nno commented on nas/graph_cnn_gp_operators.py
> +        layer_params = {'layer_type': type, 'drop': randint(1, (requirements.max_drop_size * 10)) / 10}
Всё это вычисление лучше делать заранее и сохранять в переменную, чтобы лучше читалось.

2022-04-26 11:17 UTC, nicl-nno commented on nas/graph_keras_eval.py
> +def generate_structure(node: Any):
Нужно пояснение в докстринге, что именно тут происходит - сходу непонятно.

2022-04-26 11:17 UTC, nicl-nno commented on nas/graph_keras_eval.py
> +def unpack(model, training_config, weights):
Лучше проставить аннотации для параметров.

2022-04-26 11:17 UTC, nicl-nno commented on nas/layer.py
> +    layer_type: str
А это по факту так? Ведь много где он сравнивается с LayerTypesIdsEnum.

В целом от енумов действительно можно отказаться для большей лакончности кода.

2022-04-26 11:17 UTC, nicl-nno commented on nas/nn_layers.py
> +def make_dense_layer(idx: int, input_layer: Any, current_node: Any):
В этих функциях тоже не хватает пояснений, с какого типа объектами идет работа (вид аннотаций или докстринга).

2022-04-27 14:44 UTC, staeros commented on nas/graph_cnn_gp_operators.py
> +                graph.nodes[destination_node_id].nodes_from.append(graph_node)
По идее не должно, потому что graph_node используется как раз только внутри условия is_residual

2022-04-27 14:55 UTC, staeros commented on cases/static_cnn_model.py
> +def add_skip_connections(graph: NNGraph):
Done

2022-04-27 14:56 UTC, staeros commented on cases/graph_icebergs_classification.py
> +        mutation_types=[single_edge_mutation],
Исправил, добавил еще cnn_simple_mutation

2022-04-27 14:56 UTC, staeros commented on cases/graph_patches_classification.py
> +    path = os.path.join(root, '_compressed_Generated_dataset.pickle')
Исправил

2022-04-27 14:56 UTC, staeros commented on cases/static_cnn_model.py
> +def create_graph(graph: NNGraph, node_type: str, params: dict, parent=None, residual_parent=None,
Исправил

2022-04-27 14:56 UTC, staeros commented on nas/graph_cnn_gp_operators.py
> +    if node.layer_params["pool_size"]:
Done

2022-04-27 16:21 UTC, nicl-nno commented on cases/graph_icebergs_classification.py
> +        mutation_types=[single_edge_mutation],
А вот эти мутации можно тоже добавить? Или они не работают?

    single_add
    single_change
    single_drop

2022-04-29 11:01 UTC, staeros commented on cases/graph_icebergs_classification.py
> +        mutation_types=[single_edge_mutation],
Проверил, работают. Добавил их в список мутаций и правило валидации для них

2022-04-29 11:02 UTC, staeros commented on nas/layer.py
> +    layer_type: str
Исправил, отказался от енумов. Так что можно этот класс просто убирать

2022-04-29 11:31 UTC, nicl-nno commented on nas/layer.py
> +    layer_type: str
Ага

2022-05-05 11:54 UTC, staeros commented on nas/graph_keras_eval.py
> +def generate_structure(node: Any):
Удалил функцию, так как она нигде не используется

2022-05-05 11:54 UTC, staeros commented on nas/nn_layers.py
> +def make_dense_layer(idx: int, input_layer: Any, current_node: Any):
Done

2022-05-05 11:54 UTC, staeros commented on nas/graph_keras_eval.py
> +def unpack(model, training_config, weights):
Функция нигде не используется, так что удалил ее

2022-05-05 11:55 UTC, staeros commented on cases/graph_patches_classification.py
> +        log=default_log(logger_name='Bayesian', verbose_level=1))
Исправил

2022-05-06 16:03 UTC, staeros commented on cases/graph_patches_classification.py
> +    print('save best graph structure...')
Done

2022-05-12 13:34 UTC, nicl-nno approved these changes

2022-05-12 13:37 UTC, merged