NAS core upgrade for the latest FEDOT version
ITMO-NSS-team/nas-fedot pull request #8
Opened 2022-09-01 14:38 UTC by staeros

2022-09-04 19:03 UTC, nicl-nno requested changes

2022-09-04 19:03 UTC, nicl-nno commented on nas/optimizer/objective/NNObjectiveEval.py
> +    # def setup_data(self, data: InputData, shuffle: bool = False, data_generator: DataGenerator = DataGenerator,
Аналогично про комментарий.

2022-09-04 19:03 UTC, nicl-nno commented on nas/optimizer/objective/NNObjectiveEval.py
> +        self._log = default_log(self)
Нужно ли переопределять?

2022-09-04 19:03 UTC, nicl-nno commented on nas/optimizer/objective/nas_cnn_optimiser.py
> +        NNGraph.INDIVIDUAL += 1
Нотация выглядит не очень удачно и не PEP8-но.

2022-09-04 19:03 UTC, nicl-nno commented on nas/utils/utils.py
> +            return True
а return false если нет?

Ну и это можно одной строчкой записать через list comprehension.

2022-09-05 14:09 UTC, staeros commented on nas/optimizer/objective/NNObjectiveBuilder.py
> +        # objective_evaluate =
Да, действительно не нужен, удалил. Изначально создавал его с расчетом на то, что под InputData для nas понадобится своя реализация сплитов, но удалось обойтись без этого.

2022-09-05 16:36 UTC, staeros commented on nas/utils/var.py
> +import os
А имеет смысл содержимое этого файла перенести в json конфиги и verbose вынести в датакласс?

2022-09-05 16:36 UTC, staeros commented on nas/optimizer/objective/NNObjectiveEval.py
> +        self._log = default_log(self)
Исправил

2022-09-05 16:40 UTC, nicl-nno commented on nas/utils/var.py
> +import os
Не принципиально.

2022-09-06 10:10 UTC, staeros commented on nas/utils/utils.py
> +    """Returns FEDOT project root folder."""
Done

2022-09-06 10:11 UTC, staeros commented on nas/optimizer/objective/NNObjectiveEval.py
> +    # def setup_data(self, data: InputData, shuffle: bool = False, data_generator: DataGenerator = DataGenerator,
Done

2022-09-06 10:18 UTC, staeros commented on nas/utils/utils.py
> +            return True
Удалил, осталось от старого функционала. Раньше использовалось в генераторах внутри InputData, сейчас удалось уйти от этого

2022-09-06 10:18 UTC, staeros commented on nas/optimizer/objective/nas_cnn_optimiser.py
> +        NNGraph.INDIVIDUAL += 1
Исправил

2022-09-06 10:52 UTC, nicl-nno approved these changes

2022-09-06 12:38 UTC, staeros commented on nas/utils/var.py
> +import os
Исправил

2022-09-06 12:38 UTC, merged